# Embeds a source file into a C++ translation unit as a raw string literal.
# The AOT translator (dolphin-tool translate) emits a verbatim copy of
# Source/Core/Core/PowerPC/AOT/aot_runtime.h into every generated aot-src
# tree; embedding the checked-in header at build time keeps that emitted copy
# and the copy the C++ runtime compiles against the same file by construction.
#
# Usage: cmake -DINPUT=<file> -DOUTPUT=<gen.cpp> -DVARIABLE=<name> -P StringifyHeader.cmake

if(NOT INPUT OR NOT OUTPUT OR NOT VARIABLE)
  message(FATAL_ERROR "StringifyHeader.cmake requires INPUT, OUTPUT and VARIABLE")
endif()

file(READ "${INPUT}" contents)
if(contents MATCHES [[\)aot_hdr"]])
  message(FATAL_ERROR "${INPUT} contains the raw-string delimiter )aot_hdr\"")
endif()

file(WRITE "${OUTPUT}" "// Generated by CMake/StringifyHeader.cmake from ${INPUT} — do not edit.
extern const char ${VARIABLE}[];
const char ${VARIABLE}[] = R\"aot_hdr(${contents})aot_hdr\";
")
